### ISSUE TITLE
无限闪屏

### ISSUE THREAD

**Issue by L4rue** [github-h/Patch_DBD#1]
无论是否使用管理员模式，打开批处理时都会无限闪屏，即出现“打开CMD窗口->关闭CMD窗口”的循环操作，此问题同样在解锁金刚平台的批处理文件中出现

**Comment by github-h** [comment]
请自行百度bat闪退，这大概率是因为win的系统不是官方正版。因修改(或者精简)了某些功能导致
同时请确保运行路径下无中文

**Comment by L4rue** [comment]
我找到原因了，是由于之前更改Path时，误删除了System32路径，导致CMD出现一点问题，现已解决
